jwt:
  secret-key: "test"
  time : 30

oauth2:
  providers:
    google:
      client-id: "<TODO>"
      client-secret: "<TODO>"
      redirect-uri: http://localhost:8080/api/v1/auth/callback
    github:
      client-id: "<TODO>"
      client-secret: "<TODO>"
      redirect-uri: http://localhost:8080/api/v1/auth/callback

database:
  mysql:
    url: jdbc:mysql://localhost:3306/bank?useSSL=false&serverTimezone=UTC
    username: app
    password: 1111
    driver-class-name: com.mysql.cj.jdbc.Driver

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}  # 환경변수가 없으면 local이 기본값