oauth2:
  providers:
    google:
      client-id: "<TODO>"
      client-secret: "<TODO>"
      redirect-uri: http://localhost:8080/api/v1/auth/callback
    github:
      client-id: "<TODO>"
      client-secret: "<TODO>"
      redirect-uri: http://localhost:8080/api/v1/auth/callback